# OpenJDK 21 이미지 사용
FROM openjdk:21-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 빌드
COPY ./build/libs/sl-0.0.1-SNAPSHOT.jar /app/app.jar

# Spring Boot 포트 개방
EXPOSE 8080

# 애플리케이션 실행 명령어 설정
ENTRYPOINT ["java", "-jar", "app.jar"]
